# Sample .travis.yml for R projects.
#
# See README.md for instructions, or for more configuration options,
# see the wiki:
#   https://github.com/craigcitro/r-travis/wiki

language: r

env:
  - global:
    - WARNINGS_ARE_ERRORS=1

notifications:
  email:
    on_success: change
    on_failure: change
